# Generated by Django 4.2.6 on 2023-10-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_genre_movie_score_movie_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=5.0),
        ),
    ]
